name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: ex_so1
      run: make ex_so1
    - name: ex_so_rastrigin
      run: make ex_so_rastrigin
    - name: ex_so_bind
      run: make ex_so_bind
    - name: ex_mo1
      run: make ex_mo1
    - name: ex_mo_dtlz2
      run: make ex_mo_dtlz2
    - name: ex_init_solutions
      run: make ex_init_solutions

    - name: CI skim test single-objective 
      run: cd ci-test-cases && make so-skim
    - name: CI skim test multi-objective 
      run: cd ci-test-cases && make mo-skim

    - name: CI address sanitizer test single-objective 
      run: cd ci-test-cases && make so-sanitizer-address
    - name: CI address sanitizer test multi-objective 
      run: cd ci-test-cases && make mo-sanitizer-address

    - name: CI thread sanitizer test single-objective 
      run: cd ci-test-cases && make so-sanitizer-thread
    - name: CI thread sanitizer test multi-objective 
      run: cd ci-test-cases && make mo-sanitizer-thread

    - name: CI UB sanitizer test single-objective 
      run: cd ci-test-cases && make so-sanitizer-ub
    - name: CI UB sanitizer test multi-objective 
      run: cd ci-test-cases && make mo-sanitizer-ub

    - name: CI clang compatibility check single-objective 
      run: cd ci-test-cases && make so-clang
    - name: CI clang compatibility check multi-objective 
      run: cd ci-test-cases && make mo-clang
